CRITICAL - 2025-05-03 18:27:18 --> Error: Class "App\Models\CategoriaModel" not found
[Method: GET, Route: crear_articulo]
in APPPATH\Controllers\ArticuloController.php on line 12.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 18:28:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
#8 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(13): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
#7 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#8 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-05-03 18:28:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: crear_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `categorias`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\ArticuloController.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:30:17 --> ParseError: syntax error, unexpected identifier "DBDriver", expecting "]"
[Method: GET, Route: crear_articulo]
in APPPATH\Config\Database.php on line 33.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\elfaro\\codeigniter\\app\\Config\\Database.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
 4 APPPATH\Controllers\ArticuloController.php(12): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:30:53 --> ParseError: syntax error, unexpected identifier "DBDriver", expecting "]"
[Method: GET, Route: crear_articulo]
in APPPATH\Config\Database.php on line 33.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\elfaro\\codeigniter\\app\\Config\\Database.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
 3 SYSTEMPATH\Model.php(155): CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
 4 APPPATH\Controllers\ArticuloController.php(12): CodeIgniter\Model->__construct()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->crear()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 18:32:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 18:32:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:19\', \'2025-05-03 18:32:19\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:19\', \'2025-05-03 18:32:19\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:19 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:19\', \'2025-05-03 18:32:19\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:19\', \'2025-05-03 18:32:19\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:19\', \'2025-05-03 18:32:19\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 18:32:26 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 18:32:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:26 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:26\', \'2025-05-03 18:32:26\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:26\', \'2025-05-03 18:32:26\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:26 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:26\', \'2025-05-03 18:32:26\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:26\', \'2025-05-03 18:32:26\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:26\', \'2025-05-03 18:32:26\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 18:32:40 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 18:32:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:40\', \'2025-05-03 18:32:40\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:40\', \'2025-05-03 18:32:40\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 18:32:40 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:40\', \'2025-05-03 18:32:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:40\', \'2025-05-03 18:32:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'Pan con queso\', \'Queso de pan\', \'Pericles\', \'aslkdfj\', NULL, \'2025-05-03 18:32:40\', \'2025-05-03 18:32:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:41:04 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:41:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:41:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:41:04\', \'2025-05-03 23:41:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:41:04\', \'2025-05-03 23:41:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:41:04 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:41:04\', \'2025-05-03 23:41:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:41:04\', \'2025-05-03 23:41:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:41:04\', \'2025-05-03 23:41:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:45:13 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:45:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:45:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:45:13\', \'2025-05-03 23:45:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:45:13\', \'2025-05-03 23:45:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:45:13 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:45:13\', \'2025-05-03 23:45:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:45:13\', \'2025-05-03 23:45:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:45:13\', \'2025-05-03 23:45:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:48:13 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:48:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:48:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:13\', \'2025-05-03 23:48:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:13\', \'2025-05-03 23:48:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:48:13 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:13\', \'2025-05-03 23:48:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:13\', \'2025-05-03 23:48:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:13\', \'2025-05-03 23:48:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:48:18 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:48:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:48:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:18\', \'2025-05-03 23:48:18\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:18\', \'2025-05-03 23:48:18\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:48:18 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:18\', \'2025-05-03 23:48:18\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:18\', \'2025-05-03 23:48:18\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:48:18\', \'2025-05-03 23:48:18\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:49:43 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:49:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:49:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:43\', \'2025-05-03 23:49:43\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:43\', \'2025-05-03 23:49:43\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:49:43 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:43\', \'2025-05-03 23:49:43\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:43\', \'2025-05-03 23:49:43\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:43\', \'2025-05-03 23:49:43\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-03 23:49:46 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-03 23:49:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: guardar_articulo]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:49:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:46\', \'2025-05-03 23:49:46\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:46\', \'2025-05-03 23:49:46\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:49:46 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:46\', \'2025-05-03 23:49:46\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:46\', \'2025-05-03 23:49:46\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (\'a\', \'a\', \'a\', \'a\', \'1\', \'2025-05-03 23:49:46\', \'2025-05-03 23:49:46\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `articulos` (`titulo`, `contenido`, `autor`, `imagen_portada`, `id_categoria`, `fecha_publicacion`, `updated_at`) VALUES (:titulo:, :contenido:, :autor:, :imagen_portada:, :id_categoria:, :fecha_publicacion:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ArticuloController.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:55:40 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "inicio.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('inicio.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('inicio', [], true)
 3 APPPATH\Controllers\ArticuloController.php(43): view('inicio', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:55:40 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "inicio.php"
[Method: GET, Route: /]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('inicio.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('inicio', [], true)
 3 APPPATH\Controllers\ArticuloController.php(43): view('inicio', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ArticuloController->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ArticuloController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-03 23:57:21 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "noticia.php"
[Method: GET, Route: noticia/1]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('noticia.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('noticia', [], true)
 3 APPPATH\Controllers\NoticiaController.php(12): view('noticia', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\NoticiaController->show('1')
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NoticiaController))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
