ERROR - 2025-05-07 00:02:13 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:02:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:02:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:13\', \'2025-05-07 00:02:13\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:13\', \'2025-05-07 00:02:13\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:02:13 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:13\', \'2025-05-07 00:02:13\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:13\', \'2025-05-07 00:02:13\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:13\', \'2025-05-07 00:02:13\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:02:58 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:02:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:02:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:58\', \'2025-05-07 00:02:58\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:58\', \'2025-05-07 00:02:58\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:02:58 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:58\', \'2025-05-07 00:02:58\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:58\', \'2025-05-07 00:02:58\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:02:58\', \'2025-05-07 00:02:58\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:14 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:14\', \'2025-05-07 00:03:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:14\', \'2025-05-07 00:03:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:14 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:14\', \'2025-05-07 00:03:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:14\', \'2025-05-07 00:03:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:14\', \'2025-05-07 00:03:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:17 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:17\', \'2025-05-07 00:03:17\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:17\', \'2025-05-07 00:03:17\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:17 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:17\', \'2025-05-07 00:03:17\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:17\', \'2025-05-07 00:03:17\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:17\', \'2025-05-07 00:03:17\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:35 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:35 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:35 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:35 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:35\', \'2025-05-07 00:03:35\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:36 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:36 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:36 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:36 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:36 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:36\', \'2025-05-07 00:03:36\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:03:56 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:03:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:56\', \'2025-05-07 00:03:56\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:56\', \'2025-05-07 00:03:56\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:03:56 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:56\', \'2025-05-07 00:03:56\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:56\', \'2025-05-07 00:03:56\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asdasd\', \'Solano@sola.xcl\', \'asdasd\', \'2025-05-07 00:03:56\', \'2025-05-07 00:03:56\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:04:14 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:04:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:04:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'rt\', \'Solano@sola.xcl\', \'r\', \'2025-05-07 00:04:14\', \'2025-05-07 00:04:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'rt\', \'Solano@sola.xcl\', \'r\', \'2025-05-07 00:04:14\', \'2025-05-07 00:04:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:04:14 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'rt\', \'Solano@sola.xcl\', \'r\', \'2025-05-07 00:04:14\', \'2025-05-07 00:04:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'rt\', \'Solano@sola.xcl\', \'r\', \'2025-05-07 00:04:14\', \'2025-05-07 00:04:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'rt\', \'Solano@sola.xcl\', \'r\', \'2025-05-07 00:04:14\', \'2025-05-07 00:04:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:04:42 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:04:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:04:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:04:42\', \'2025-05-07 00:04:42\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:04:42\', \'2025-05-07 00:04:42\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:04:42 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:04:42\', \'2025-05-07 00:04:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:04:42\', \'2025-05-07 00:04:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:04:42\', \'2025-05-07 00:04:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:06:30 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:06:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:06:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:06:30\', \'2025-05-07 00:06:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:06:30\', \'2025-05-07 00:06:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:06:30 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:06:30\', \'2025-05-07 00:06:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:06:30\', \'2025-05-07 00:06:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:06:30\', \'2025-05-07 00:06:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:07:30 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:07:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:07:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:07:30\', \'2025-05-07 00:07:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:07:30\', \'2025-05-07 00:07:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:07:30 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:07:30\', \'2025-05-07 00:07:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:07:30\', \'2025-05-07 00:07:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'sad\', \'Solano@sola.xcl\', \'sd\', \'2025-05-07 00:07:30\', \'2025-05-07 00:07:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-05-07 00:07:39 --> mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list' in C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\elfaro\codeigniter\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\elfaro\codeigniter\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\elfaro\codeigniter\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\elfaro\codeigniter\system\BaseModel.php(750): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\elfaro\codeigniter\app\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
#10 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
#11 C:\xampp\htdocs\elfaro\codeigniter\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\elfaro\codeigniter\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\elfaro\codeigniter\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2025-05-07 00:07:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
[Method: POST, Route: guardar_contacto]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:07:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asda\', \'Solano@sola.xcl\', \'asasd\', \'2025-05-07 00:07:39\', \'2025-05-07 00:07:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asda\', \'Solano@sola.xcl\', \'asasd\', \'2025-05-07 00:07:39\', \'2025-05-07 00:07:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-05-07 00:07:39 --> [Caused by] mysqli_sql_exception: Unknown column 'fecha_contacto' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asda\', \'Solano@sola.xcl\', \'asasd\', \'2025-05-07 00:07:39\', \'2025-05-07 00:07:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asda\', \'Solano@sola.xcl\', \'asasd\', \'2025-05-07 00:07:39\', \'2025-05-07 00:07:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (\'asda\', \'Solano@sola.xcl\', \'asasd\', \'2025-05-07 00:07:39\', \'2025-05-07 00:07:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contactos` (`nombre`, `email`, `mensaje`, `fecha_contacto`, `updated_at`) VALUES (:nombre:, :email:, :mensaje:, :fecha_contacto:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(750): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\ContactoController.php(26): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ContactoController->guardar()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ContactoController))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
